#!/bin/sh
### BEGIN INIT INFO
# Provides:          motion-starter
# Required-Start:    $local_fs 
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: motion-starter
### END INIT INFO

export PATH=$PATH:/usr/local/bin:/opt/node/bin

case "$1" in
  start)
  exec forever --uid "discoverer" --sourceDir=/home/pi/pings -a -p /var/run start noam.sh
  ;;

  stop)
  exec forever -p /var/run stop discoverer
  ;;
esac

exit 0

